version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: computers
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  greenbone-notification:
    image: greenbone/exercise-admin-notification
    ports:
      - "8080:8080"

  api:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_TYPE: postgres
      DATABASE_URL: "host=postgres user=admin password=password dbname=computers port=5432 sslmode=disable"
      NOTIFICATION_URL: http://greenbone-notification:8080
      PORT: 8081
    depends_on:
      - postgres
      - greenbone-notification
    restart: unless-stopped

volumes:
  postgres_data: